#! /bin/sh

source ./activate

todo.sh add "Enquanto nao atualizar as acoes colocar uma edicao no overview"
todo.sh add "Melhorar o overview para mostrar mais dados"
todo.sh add "Colocar as contas de op gain and loss no buy"
todo.sh add "Atualizar automaticamente o saldo em conta"
todo.sh add "Colocar um intent na experience [Neste primeiro momento apenas sera de uso informativo na tabela]"
todo.sh add "Permitir a ordenacao pelo favoritismo"
todo.sh add "Nao permitir vender acao sem possuir acao [e outras validações]"
todo.sh add "Sistema de notas: Ir clocando notas no focus, uma lista de notas... possivelmente com alguns dados para nossa analize. Ir pensando... [Feito o inicial, simples...]"
todo.sh add "Operacao pente fino"
todo.sh add "Fazer quick buy/quick sell a partir de exp e buy"
todo.sh add "Fazer um conglomerado das compras/lucros de cada acao para a tela de overview [opcao de join?]"
todo.sh add "Atualizar o resume quando alguma alteração ocorrer no stock price"
todo.sh add "Colocar mais informacoes sobre a empresa na acao."
todo.sh add "Pensar transformar o buy em venda. Colocar um status na venda de [realizado] e fazer os estudos na venda. Parece mais razoável. A venda pode se tornar realizada depois de arquivada mesmo."
todo.sh add "Finalizar o novo esquema de sell."
todo.sh add "Colocar uma relacao real entre compra e venda."
todo.sh add "Colocar notas no sell."
todo.sh add "Refazer a conta do equity para considerar o valor das ações compradas."
todo.sh add "Geral!"
todo.sh add "Onde o numero ser negativo motrar o texto vermelho"
todo.sh add "Colocar link para fundamentus."
todo.sh add "Colocar favoritos no sell e no buy?"
todo.sh add "Colocar data no Notes e permitir apagar/editar uma nota."
todo.sh add "Mostrar em algum lugar o quanto o ganho ou perda da acao equivale no total equity"
todo.sh add "Fazer "Paper Buy/Paper Sell""
todo.sh add "Delete no Paper Operation"
todo.sh add "Update de libs"
todo.sh add "Performance boost and refactorings"
todo.sh add "Fazer manager para acertar as operacoes existentes"
todo.sh add "Experimentar possibilidade de testes unitarios no cliente web - Nao usar por enquanto"
todo.sh add "Conta de usuario"
todo.sh add "Colocar mensagens motivadoras"
todo.sh add "Ver unsubscribes de novo!"
todo.sh add "Fazer um outro average stocks com apenas as operacoes ativas"
todo.sh add "Colocar a categoria da operacao como uma configuracao do usuario. Aproveitar a logica existente para fazer uma checagem ou autocompletagem a pedido do usuario."
todo.sh add "Fazer um historico [principalmente com vendas]"
todo.sh add "Fazer filtros para nao mostrar os itens arquivados ou mostra-los"
todo.sh add "Revalidar e conferir todas as contas e dados mostrados + refazer os testes unitarios."
todo.sh add "Refatorar os objetos. Pensar em uma maneira melhor de organizar o codigo pois a classe esta ficando gigante, com qse 1000 linhas [isso eh muito para python?]."
todo.sh add "Colocar na operacao o campo "razao". Com o motivo para entrar e sair do trade."
todo.sh add "Colocar um upload do grafico na operacao."
todo.sh add "Colocar data limite [ou limites, com avisos] da hora de vender a ação"
todo.sh add "Pensar num esquema de atualizar as operacoes sem precisar salvar"
todo.sh add "Ver atualizacao automatica das acoes"
todo.sh add "Refazer o daytrade. Por enquanto colocar apenas um indicativo de quando é dt.????"
todo.sh add "Colocar internacionalizacao"
todo.sh add "Testes unitarios"
